# Generated by Django 2.2 on 2021-01-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='good_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app_shops.Good'),
        ),
    ]
