# Generated by Django 2.2 on 2021-01-21 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0003_auto_20210121_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='shop_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop_sales', to='app_shops.Shop'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='good_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='good_sales', to='app_shops.Good'),
        ),
    ]
