# Generated by Django 2.2 on 2021-01-21 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0005_auto_20210121_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='good_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app_shops.Good'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shops.Shop'),
        ),
    ]
