# Generated by Django 2.2 on 2021-01-22 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0009_auto_20210121_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='shop_id',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='good_id',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='shop_id',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='good_id',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
