# Generated by Django 2.2 on 2021-01-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0012_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_shops.Shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.FloatField(default=0, verbose_name='Sale price'),
        ),
    ]
