# Generated by Django 2.2 on 2020-11-30 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='Пользователь')),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000, verbose_name='news')),
                ('body', models.TextField(verbose_name='Текст новости')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')], verbose_name='Активно')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.NewsComments')),
            ],
        ),
    ]
