# Generated by Django 2.2 on 2020-11-30 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='comments',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_app.NewsComments'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=1, verbose_name='Активно'),
        ),
    ]
