# Generated by Django 2.2 on 2021-02-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0005_auto_20210223_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='authors', to='app_catalog.Author'),
        ),
    ]
